app <- ShinyDriver$new("../../", loadTimeout =  100000)
app$snapshotInit("upload_and_spatial_for_100")

app$setInputs(tabs = "Analysis")
app$setInputs(filetype_tabs = "GPKG")
app$uploadFile(uploaded_gpkg = "geo_100.gpkg")
app$snapshot()
app$setInputs(analyses_types_tabs = "Spatial")
app$setInputs(visualize_button = "click")
app$snapshot()
Sys.sleep(6)
app$setInputs(cumul_distr_percent = 95)
app$setInputs(map_rez = 0.05)
app$setInputs(mapped_column = "Mean fishing hours")
app$setInputs(re_visualize_button = "click")
app$snapshot()