app <- ShinyDriver$new("../../", loadTimeout =  100000)
app$snapshotInit("upload_geo100_and_clip")

app$setInputs(tabs = "Analysis")
app$setInputs(filetype_tabs = "GPKG")
app$uploadFile(uploaded_gpkg = "geo_100.gpkg")
app$uploadFile(second_uploaded_gpkg = "overlay.gpkg")
app$setInputs(second_gpkg_layer = "sanctuary")
app$setInputs(clip = TRUE)
app$setInputs(analyses_types_tabs = "Spatial")
app$setInputs(visualize_button = "click")
Sys.sleep(3)
app$snapshot()
app$setInputs(analyses_types_tabs = "Descriptive")
app$setInputs(summaries = "month")
app$setInputs(summarize_button = "click")
Sys.sleep(3)
app$snapshot()